
language: objective-c
osx_image: xcode10.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

addons:
  homebrew:
    packages:
    - carthage

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks
    - carthage update --verbose | xcpretty -c

script:
    - set -o pipefail

    - echo Build the framework
    - xcodebuild clean build -scheme 'libavif' -sdk macosx -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libavif iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libavif tvOS' -sdk appletvsimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -scheme 'libavif watchOS' -sdk watchsimulator -configuration Debug | xcpretty -c

    - echo Build the example app
    - xcodebuild build -scheme 'libavifExample' -sdk macosx -configuration Debug | xcpretty -c